#!/bin/bash
#This file is to run an alias for gzip rubble, gzip does not work for directories and was an oversight

#This checks if you fixed the rubble, if rubble.gz exists then you didn't fix yet
if [ -d hospital ]
then 
	echo "You used lowecase h, you should know that capitalization matters in the shell. Try using capital H."
	rmdir hospital
fi
if [ -d Hospital ]
then 
	echo "Awesome job! Give the Hospital a visit to see what you've accomplished."
	cat .DrPhil > Hospital/@DrPhil 2>/dev/null #Makes Dr Phil appear by using a hidden script
	CompQuest2=1 #Putting this here for a possible achievement system, can check them off like checkboxes
	cat .sign > Hospital/sign 2>/dev/null #Makes a sign with new info appear
	cat ../UPTOWN/FIRST_STREET/Pk_Square_Remains/.secondSarah > ../UPTOWN/FIRST_STREET/Pk_Square_Remains/@Sarah #creaties the new non-injured sarah after the hospital is constructed
	rm ../UPTOWN/FIRST_STREET/Pk_Square_Remains/@InjuredSarah 2>/dev/null #removes old InjuredSarah file
else
	echo "I don't see a Hospital built. Make sure you used a capital H. You can always talk to Steven if you need a refresher."
fi
