#!/bin/bash
#This file is used to validate the use of mkdir as a skill, it also makes characters appear and changes the environment

#This checks if you used a lowercase letter, then tells you that capitalization is important in the shell.
if [ -d hospital ]
then 
	echo "You used lowecase h, you should know that capitalization matters in the shell. Try again using capital H. 'hospital' has been removed."
	rm -r hospital
fi
if [ -d Hospital ]
then 
	echo "Awesome job! Give the Hospital a visit to see what you've accomplished."
	cat .DrPhil > Hospital/@DrPhil 2>/dev/null #Makes Dr Phil appear by using a hidden script
	CompQuest2=1 #Putting this here for a possible achievement system, can check them off like checkboxes
	cat .sign > Hospital/sign 2>/dev/null #Makes a sign with new info appear
	rm ../UPTOWN/FIRST_STREET/Pk_Square_Remains/@InjuredSarah 2>/dev/null #removes old InjuredSarah file
	cp .secondSarah Hospital/@Sarah #Makes Sarah appear in the hospital
else
	echo "I don't see a Hospital built. Make sure you used a capital H. You can always talk to Steven if you need a refresher."
fi
