#!/bin/bash
#This guy will teach how to interact with rubble

a=0 #this is used to trigger a secondary prompt
x=1 #this is used to trigger the exit status

function menu () {
        printf "Option 1 [Hey man, are you alright?]\nOption 2 [What can I do to help?]\nOption 3 [Thank you, I'll do my best.]\n"
        read -p "(Enter 1, 2, or 3): " choice
}
while [ $x -eq 1 ]
do
if [ $a -eq 0 ]
then
        printf "Hey! Hey you! You seem to be fine, can you help these citiczens? They're trapped under rubble and I'm too injured to move...\n"
        menu
        a=1
else
        printf "Anything else?\n"
        menu
fi
case "$choice" in
   1) echo "Yeah I'll be okay, but there are people under the rubble! Can you help them?"
   ;;
   2) echo "You can use the 'ungz rubble' command the free them."
   ;;
   3) echo "Good luck! Remember, use ungz target to clear the rubble. Think 'ungodzilla' or 'ungunzip' if you're technical."
      x=0
   ;;
   *) echo "I don't know what that is..."
   ;;
esac
done

