#!/bin/bash
#This file is to run an alias for gzip rubble, gzip does not work for directories and was an oversight

#This checks if you fixed the rubble, if rubble.gz exists then you didn't fix yet
if [ -f rubble.gz ]
then 
	echo "You still need to clear the rubble, talk to Sarah if you forgot what to do..."
else 
	echo "You did it! You cleared the rubble and saved someone trapped under the rubble. How heroic!"
	rm rubble 2>/dev/null #Removes the rubble completely
	cat .Timothy > @Timothy 2>/dev/null #Makes an NPC child appear by using a hidden file containing script contents
	CompQuest1=1 #Putting this here for a possible achievement system, can check them off like checkboxes or use them to gate DOWNTOWN
	cat .sign > sign 2>/dev/null #Makes a sign with new info appear
	cat ../../../Dans_Yard/.secondDan > ../../../Dans_Yard/@Dan #Changes the Dan NPC to continue directing the storyline
fi
