#!/bin/bash

a=0 #this is used to trigger a secondary prompt
x=1 #this is used to trigger the exit status

function menu () {
	printf "Option 1 [What's happened Dan?]\nOption 2 [How can I help?]\nOption 3 [Goodbye Dan.]\n"
	read -p "(Enter 1, 2 or 3): " choice
}
while [ $x -eq 1 ]
do
if [ $a -eq 0 ]
then
	printf "MY HOUSE!!!!!! MY HOUUUUUUUSEEEE!!!!!!!! Linus are you seeing this?? Can you please help me?\n"
	menu 	
	a=1
else
        printf "Anything else?\n"
	menu
fi
case "$choice" in
   1) echo "Yeah, I heard some huge rumbles and something about a MONSTER! It stepped on my house and I'm so scared! Linus, you gotta help me."
   ;;
   2) echo "I know Sarah went to UPTOWN's FIRST_STREET, do you think you could find her? I think she may be able to fix my poor house."
   ;;
   3) echo "Goodbye."
      x=0
   ;;
   *) echo "I don't know what that is..."
   ;;
esac
done

