#!/bin/bash

a=0 #this is used to trigger a secondary prompt
x=1 #this is used to trigger the exit status

while [ $x -eq 1 ]
do
if [ $a -eq 0 ]
then
        read -p 'MY HOUSE!!!!!! MY HOUUUUUUUSEEEE!!!!!!!! Linus are you seeing this?? Can you please help me?' choice
        a=1
else
        read -p "Anything else? " choice
fi
case "$choice" in
   1) echo "You picked option 1"
   ;;
   2) echo "You picked option 2"
   ;;
   3) echo "Goodbye."
      x=0
   ;;
   *) echo "I don't know what that is..."
   ;;
esac
done

