#!/bin/bash

#This NPC is here to teach you about rm, it will allow the player full and almighty power needed to remove Godzilla entirely from the Directoropolis. To be paired later with the chmod command

a=0 #this is used to trigger a secondary prompt
x=1 #this is used to trigger the exit status

function menu () {
        printf "Option 1 [I was sent by Bobert.]\nOption 2 [I was sent by Dan.]\nOption 3 [I was sent by Loberg.]\n"
        read -p "(Enter 1, 2, or 3): " choice
}
while [ $x -eq 1 ]
do
if [ $a -eq 0 ]
then
        printf "Halt! This is a resttricted area. Are you Linus? Tell me who sent you, and answer carefully.\n"
        menu
        a=1
else
        printf "Anything else?\n"
        menu
fi
case "$choice" in
   1) echo "*Information 1*"
   ;;
   2) echo "*Information 2*"
   ;;
   3) echo "*Information 3*"
      x=0
   ;;
   *) echo "I don't know what that is..."
   ;;
esac
done
