#!/bin/bash
echo "Hey Linus! How are you doing? I'm surprised you slept through all of the noise!"
echo "Have you seen Dan's house? It's crazy! Do you think you could check on him for me?"










































#@Sammy is a person! (script)  try using . @Sammy to interact with him.
